### PR TITLE
hotfix/extension-exception-view-tweaks

### PR DESCRIPTION
**Pull request by shayanaijaz**
## Overview

Tweaks to the Extension and Exception view pages based on feedback

## Related

…

## Changes

- Tweaked ordering of fields and added fields to display in Exception and Extension detail views.
- Added another `JOIN` to the exceptions query to get the full data file name

## Testing

1. In order to mock some data for local testing make changes to the following files

`apcd_cms/src/apps/admin_exception/views.py:`

<details>
       <summary>View Snippet</summary>

Add the following to the top of the file:

`import datetime`

 Replace line 36 with the following:

  ```js
exception_content = [
        (
            1,                                                                      # exception_id
            1,                                                                      # submitter_id
            'Joe Harrison',                                                         # requestor_name
            'threshold',                                                            # request_type
            'Currently, our claims process does not require a street address.',     # explanation_justification
            'pending',                                                              # outcome
            datetime.datetime(2022, 12, 20, 11, 10, 34, 598953),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'jharri66',                                                             # user_id
            'joseph.harrison@uth.tmc.edu',                                          # requestor_email
            'ME',                                                                   # data_file
            'CDLME023',                                                             # field_number
            60,                                                                     # required_threshold
            30,                                                                     # requested_threshold
            datetime.date(2023, 12, 31),                                            # requested_expiration_date
            None,                                                                   # approved_threshold
            None,                                                                   # approved_expiration_date
            None,                                                                   # status
            None,                                                                   # notes
            'CHCD',                                                                 # org_name
            'Provider'                                                              # data_file_name
        ),
        (
            2,                                                                      # exception_id
            2,                                                                      # submitter_id
            'Kenneth Nguyen',                                                       # requestor_name
            'other',                                                                # request_type
            'We need an exception from submitting a provider' 
            'file because we do not have a provider network.',                      # explanation_justification
            'approved',                                                             # outcome
            datetime.datetime(2022, 12, 20, 15, 35, 10, 171666),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000001,                                                               # payor_code
            'nguyken',                                                              # user_id
            'kenneth.nguyen@uth.tmc.edu',                                           # requestor_email
            None,                                                                   # data_file
            None,                                                                   # field_number
            None,                                                                   # required_threshold
            None,                                                                   # requested_threshold
            datetime.date(2023, 12, 31),                                            # requested_expiration_date
            None,                                                                   # approved_threshold
            None,                                                                   # approved_expiration_date
            None,                                                                   # status
            None,                                                                   # notes
            'CHCD',                                                                 # org_name
            'Provider'                                                              # data_file_name
        ),
        (
            3,                                                                      # exception_id
            1,                                                                      # submitter_id
            'Joe Harrison',                                                         # requestor_name
            'threshold',                                                            # request_type
            'Our current claims process will not initially be' 
            'able to meet the threshold.',                                          # explanation_justification
            'denied',                                                               # outcome
            datetime.datetime(2022, 12, 20, 15, 40, 30, 646609),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'jharri66',                                                             # user_id
            'joseph.harrison@uth.tmc.edu',                                          # requestor_email
            'MC',                                                                   # data_file
            'CDLME033',                                                             # field_number
            90,                                                                     # required_threshold
            50,                                                                     # requested_threshold
            datetime.date(2023, 12, 31),                                            # requested_expiration_date
            None,                                                                   # approved_threshold
            None,                                                                   # approved_expiration_date
            None,                                                                   # status
            None,                                                                   # notes
            'CHCD',                                                                 # org_name
            'Provider'                                                              # data_file_name
        ),
        (
            4,                                                                      # exception_id
            58,                                                                     # submitter_id
            'Devon Miller',                                                         # requestor_name
            'threshold',                                                            # request_type
            'This field is not required in our intake system, so we will not' 
            'be able to meet the desired threshold for the provider file to' 
            'pass submission validation - we are providing as much data' 
            'as is available.',                                                     # explanation_justification
            'approved',                                                             # outcome
            datetime.datetime(2023, 1, 19, 14, 31, 57, 232817),                     # created_at
            datetime.datetime(2023, 1, 19, 14, 46, 23, 900739),                     # updated_at
            'LINNATLF',                                                             # submitter_code
            20000051,                                                               # payor_code
            'dias',                                                                 # user_id
            'dias@lfg.com',                                                         # requestor_email
            'PV',                                                                   # data_file
            'CDLPV021',                                                             # field_number
            100,                                                                    # required_threshold
            0,                                                                      # requested_threshold
            datetime.date(2023, 12, 31),                                            # requested_expiration_date
            0,                                                                      # approved_threshold
            datetime.date(2023, 12, 31),                                            # approved_expiration_date
            'approved',                                                             # status
            None,                                                                   # notes
            'CHCD',                                                                 # org_name
            'Medical Provider'                                                      # data_file_name
        )
    ]
  ```

Replace line 71 with the following: 

  ```js
submission_logs = [ ]
  ```
</details>

`apcd_cms/src/apps/admin_extensions/views.py:`

<details>
       <summary>View Snippet</summary>

Add the following to the top of the file:

`import datetime`

 Replace line 36 with the following :

  ```js
extension_content = [
        (
            1,                                                                      # extension_id
            1,                                                                      # submitter_id
            datetime.date(2023, 12, 31),                                            # current_expected_date
            datetime.date(2023, 12, 31),                                            # requested_target_date
            None,                                                                   # approved_expiration_date
            'other',                                                                # extension_type
            None,                                                                   # applicable_data_period
            None,                                                                   # status
            'pending',                                                              # outcome
            datetime.datetime(2022, 12, 20, 11, 10, 34, 598953),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'jharri66',                                                             # user_id
            'Joe Harrison',                                                         # requestor_name
            'joseph.harrison@uth.tmc.edu',                                          # requestor_email
            'Currently, our claims process does not require a street address.',     # explanation_justification
            None,                                                                   # notes
            'CHCD'                                                                  # org_name
        ),
        (
            2,                                                                      # extension_id
            2,                                                                      # submitter_id
            datetime.date(2023, 12, 31),                                            # current_expected_date
            datetime.date(2023, 12, 31),                                            # requested_target_date
            None,                                                                   # approved_expiration_date
            'other',                                                                # extension_type
            None,                                                                   # applicable_data_period
            None,                                                                   # status
            'pending',                                                              # outcome
            datetime.datetime(2022, 12, 20, 11, 10, 34, 598953),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'nguyken',                                                              # user_id
            'Kenneth Nguyen',                                                       # requestor_name
            'kenneth.nguyen@uth.tmc.edu',                                           # requestor_email
            'Currently, our claims process does not require a street address.',     # explanation_justification
            None,                                                                   # notes
            'CHCD'                                                                  # org_name
        ),
        (
            3,                                                                      # extension_id
            1,                                                                      # submitter_id
            datetime.date(2023, 12, 31),                                            # current_expected_date
            datetime.date(2023, 12, 31),                                            # requested_target_date
            None,                                                                   # approved_expiration_date
            'other',                                                                # extension_type
            None,                                                                   # applicable_data_period
            None,                                                                   # status
            'pending',                                                              # outcome
            datetime.datetime(2022, 12, 20, 11, 10, 34, 598953),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'nguyken',                                                              # user_id
            'Kenneth Nguyen',                                                       # requestor_name
            'kenneth.nguyen@uth.tmc.edu',                                           # requestor_email
            'Currently, our claims process does not require a street address.',     # explanation_justification
            None,                                                                   # notes
            'CHCD'                                                                  # org_name
        ),
        (
            4,                                                                      # extension_id
            58,                                                                     # submitter_id
            datetime.date(2023, 12, 31),                                            # current_expected_date
            datetime.date(2023, 12, 31),                                            # requested_target_date
            None,                                                                   # approved_expiration_date
            'other',                                                                # extension_type
            None,                                                                   # applicable_data_period
            None,                                                                   # status
            'pending',                                                              # outcome
            datetime.datetime(2022, 12, 20, 11, 10, 34, 598953),                    # created_at
            None,                                                                   # updated_at
            'TESTGOLD',                                                             # submitter_code
            10000000,                                                               # payor_code
            'dias',                                                                 # user_id
            'Devon Miller',                                                         # requestor_name
            'dias@lfg.com',                                                         # requestor_email
            'Currently, our claims process does not require a street address.',     # explanation_justification
            None,                                                                   # notes
            'CHCD'                                                                  # org_name
        )
    ]
  ```

</details>

3. Open [http://localhost:8000/administration/list-exceptions](http://localhost:8000/administration/list-exceptions) and [http://localhost:8000/administration/list-extensions](http://localhost:8000/administration/list-extensions)
4. Open the detail modals on the pages and confirm fields look similar to screenshots

## UI

Extension Details:

Screen Shot 2023-02-07 at 12 59 43 PM

Exception Details:

Screen Shot 2023-02-07 at 12 59 57 PM

### CODE REVIEW

**Review by sophia-massie — COMMENTED** [review]
Would it make sense to do something like this for both exceptions and extensions to make nicer looking output?       
```
def _set_exceptions(exception):
            return {
                'exception_id': exception[0],
                'submitter_id': exception[1],
                'requestor_name': exception[2],
                'request_type': exception[3].title() if exception[3] != None else exception[3],
                'explanation_justification': exception[4],
                'outcome': exception[5].title() if exception[5] != None else exception[3],
                'created_at': exception[6],
                'updated_at': exception[7],
                'submitter_code': exception[8],
                'payor_code': exception[9],
                'user_id': exception[10],
                'requestor_email': exception[11],
                'data_file': exception[12],
                'field_number': exception[13],
                'required_threshold': exception[14],
                'requested_threshold': exception[15],
                'requested_expiration_date': exception[16],
                'approved_threshold': exception[17],
                'approved_expiration_date': exception[18],
                'status': exception[19].title() if exception[19] != None else exception[19],
                'notes': exception[20],
                'org_name': exception[21],
                'data_file_name': exception[22]
            }

```

**Comment by shayanaijaz** [comment]
> Would it make sense to do something like this for both exceptions and extensions to make nicer looking output?
> 
> ```
> def _set_exceptions(exception):
>             return {
>                 'exception_id': exception[0],
>                 'submitter_id': exception[1],
>                 'requestor_name': exception[2],
>                 'request_type': exception[3].title() if exception[3] != None else exception[3],
>                 'explanation_justification': exception[4],
>                 'outcome': exception[5].title() if exception[5] != None else exception[3],
>                 'created_at': exception[6],
>                 'updated_at': exception[7],
>                 'submitter_code': exception[8],
>                 'payor_code': exception[9],
>                 'user_id': exception[10],
>                 'requestor_email': exception[11],
>                 'data_file': exception[12],
>                 'field_number': exception[13],
>                 'required_threshold': exception[14],
>                 'requested_threshold': exception[15],
>                 'requested_expiration_date': exception[16],
>                 'approved_threshold': exception[17],
>                 'approved_expiration_date': exception[18],
>                 'status': exception[19].title() if exception[19] != None else exception[19],
>                 'notes': exception[20],
>                 'org_name': exception[21],
>                 'data_file_name': exception[22]
>             }
> ```

I like that. I think a little better approach would be to create a utility function that handles title casing the words for us. I can put that in when I have a little bit more time and after everything else has been tested

**Review by edmondsgarrett — CHANGES_REQUESTED** [review]
Modal looks to display the data correctly, and fields look good. 

I think the footers on these modals are too big, and look to take up even more space with less data in the modal.

image

**Review by edmondsgarrett — COMMENTED** [review]
Re-reviewed because I had neglected to check out the correct branch, my note on footer size in my last review still stands.

**Review by edmondsgarrett — CHANGES_REQUESTED** [review]
That footer-looking part on the modal is still big, looks like it scales with the window size (smaller windows, modal looks more appropriate, larger windows, about half of the modal is white space below that divider)

**Review by sophia-massie — CHANGES_REQUESTED** [review]
The modal Extensions View Details is only showing the information for the first entry in the extension list on each modal no matter which one you pick.

**Review by sophia-massie — APPROVED** [review]
LGTM!

**Review by edmondsgarrett — APPROVED** [review]
LGTM!

**Pull request merged**
