### PR TITLE
Task/WP-746-styles-primary-color-blue

### PR DESCRIPTION
**Pull request by sophia-massie**
## Overview

Updates @tacc/core-styles package to use expected color

## Related

- [WP-746](https://tacc-main.atlassian.net/browse/WP-746)

## Changes

…

## Testing

1. Stop all containers and rebuild
2. npm ci, npm run build (there will be new warnings on build - this is expected)
3. Run client and make sure no breaking changes in styles across the site
4. Make sure links/primary color is set to blue
5. In console, check that color: var(--global-color-link-on-light--normal); is computed to # 039

## UI

###Select fields as links turn to blue
Screenshot 2024-11-05 at 2 45 19 PM

###Button colors change to blue
Screenshot 2024-11-05 at 2 45 55 PM

###Nav bar is now blue
Screenshot 2024-11-05 at 2 46 25 PM

###Pagination is now blue
Screenshot 2024-11-05 at 2 47 11 PM

### All buttons should use core-components/Button rather than Reactstrap component Button in order to pick up styles
Screenshot 2024-11-05 at 2 47 55 PM

### CODE REVIEW

**Review by happycodemonkey — APPROVED** [review]
This looks great!

**Review by chandra-tacc — APPROVED** [review]

**Review by happycodemonkey — APPROVED** [review]
Looks great!

**Comment by sophia-massie** [comment]
My concern is that is seems to be breaking the custom css modules imports for the components. The upgrade in Core-Styles required a postcss-preset-env upgrade and I'm not sure how to configure this to either a) allow us to continue using css modules or b) change the css modules to a format it expects

**Review by chandra-tacc — APPROVED** [review]
LGTM

**Comment by sophia-massie** [comment]
> My concern is that is seems to be breaking the custom css modules imports for the components. The upgrade in Core-Styles required a postcss-preset-env upgrade and I'm not sure how to configure this to either a) allow us to continue using css modules or b) change the css modules to a format it expects

This has been resolved. This will require rebuilding the containers and collecting static in the core-cms container to pick up changes

**Review by chandra-tacc — APPROVED** [review]
tested and LGTM

**Pull request merged**
