### PR TITLE
change page title instructions

### PR DESCRIPTION
**Pull request by davidmtacc**
## Overview
Change 'Filter by Organization' to 'View users by Organization'
…

## Related

…

## Changes
Change title before dropdown
…

## Testing

1. Tested with fake data and commented out login as admin requirement

## UI

…

### CODE REVIEW

**Review by jmartinez-tacc — APPROVED** [review]
LGTM!

**Review by sophia-massie — CHANGES_REQUESTED** [review]
The instructions look great! Look like some things Frank requested be removed from view_users/views.py snuck back into the code. These lines need to be removed as per PR #90:

On view_users/views.py remove:

- _set_modal_content on line 40
- actions = "View" on line 22
- remove entire line 51 user_view = [usr for usr in user_content if usr[1] == user[0]]

**Comment by davidmtacc** [comment]
I have removed unnecessary lines as suggested.

**Review by sophia-massie — APPROVED** [review]
LGTM!

**Comment by sophia-massie** [comment]
Remove line `user_view = [usr for usr in user_content if usr[1] == user[0]] from view_users.py`
Add back `context['rows'].append(_set_user(user,)) ` to the get_context_data function as it was before the last commit

**Pull request merged**
