### PR TITLE
task/FP-1906 View Registrations Modal

### PR DESCRIPTION
**Pull request by edmondsgarrett**
## Overview
Added functionality, updated styling, and isolated HTML for view registration modal
…

## Related

- [FP-1906](https://jira.tacc.utexas.edu/browse/FP-1906)
…

## Changes
- Isolated HTML and styles for view registration modal
- Added functionality (util functions, context variables) to app view for modal
…

## Testing

1. In `src/apps/admin_regis_table/views.py`, replace lines 20-22 with the following snippet:
     <details><summary>Snippet</summary>
     
          import datetime
          registrations_content = [
            (
                1,                                  #registration_id
                datetime.date(2022, 8, 3),          #posted_date
                12023,                              #applicable_period_start
                122023,                             #applicable_period_end
                True,                               #file_me
                True,                               #file_pv
                True,                               #file_mc
                True,                               #file_pc
                False,                              #file_dc
                True,                               #submitting_for_self
                'SFTP',                             #submission_method
                'active',                           #registration_status
                'insurance carrier',                #org_type
                'Golden Rule Insurance Company',    #business_name
                '7440 Woodland Drive',              #mail_address
                'Indianpolis',                      #city
                'IN',                               #state
                '46278     '                        #zip
            ),
            (
                1,                                  #registration_id
                datetime.date(2022, 8, 3),          #posted_date
                12023,                              #applicable_period_start
                122023,                             #applicable_period_end
                True,                               #file_me
                True,                               #file_pv
                True,                               #file_mc
                True,                               #file_pc
                False,                              #file_dc
                True,                               #submitting_for_self
                'SFTP',                             #submission_method
                'active',                           #registration_status
                'insurance carrier',                #org_type
                'Golden Rule Insurance Company',    #business_name
                '7440 Woodland Drive',              #mail_address
                'Indianpolis',                      #city
                'IN',                               #state
                '46278     '                        #zip
            )
        ]
        registrations_entities = [
            (
                5, 1, 5, 46, 11111, 0, 5, 'Garretts Test Business 2', '11-0001111'
            ),
            (
                5, 1, 50000, 47, 1010, 1101, 1, 'A Second Test Entity', '00-0000000'
            )
        ]
        registrations_contacts = [
            (
                52,
                1,
                False,
                'Test Role',
                'Garrett Test Tester',
                '2222222222',
                'notarealemail@emailplace.email'
            ),
            (
                53,
                1,
                False,
                'A 2nd Test Role',
                'Test Garrett 2 Test',
                '5555555555',
                'testemail@testemail.emailtest'
            ),
            (
                54,
                1,
                True,
                'A 3rd and final test role',
                'Test 3rd Role Name Garrett',
                '0000000000',
                None
            )
          ]
        
    </details>
2. Open http://localhost:8000/administration/list-registration-requests/
3. Click on the 'View' button in the last column of either row
4. Confirm the modal content looks like the video below
5. Confirm the modal only closes via 'Close' button in the modal footer

## UI
[Screen Recording 2022-11-09 at 3.03.52 PM.zip](https://github.com/TACC/Core-CMS-Custom/files/9975098/Screen.Recording.2022-11-09.at.3.03.52.PM.zip)

…

### CODE REVIEW

**Comment by Strmiska** [comment]
The modal appears similarly to the video however:
1. I don't see a close button at the bottom. Is there a reason we can't have an X at the top right of the modal?
2. We should probably change the wording for "Select to receive system notifications" under Contacts when displaying wether or not that's been checked.
3. Is it possible to make the modal a bit bigger so you can read more of the form at once?

**Review by wesleyboar — COMMENTED** [review]
Direction from [FP-1906](https://jira.tacc.utexas.edu/browse/FP-1906), reworded to be clearer about data content:

**Modals**
"Style modal itself like Core-Portal." Feel free to copy Portal styles.

**Forms**
1. Do not use form markup[^1] not classes[^2] to show data.[^3]
2. Use appropriate markup e.g. [description list elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl), [table elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#table_content).
3. Apply [`c-data-list(...)` classes](https://github.com/TACC/Core-Styles/blob/main/src/lib/_imports/components/c-data-list.css) to appropriate elements.

<details><summary>Example</summary>

```
<table class="c-data-list c-data-list--is-vert c-data-list--is-narrow">
    <tbody>
      <tr>
        <th class="c-data-list__key">Processors</th>
        <td class="c-data-list__value">8280</td>
      </tr>
      <tr>
        <th class="c-data-list__key">Processor Type</th>
        <td class="c-data-list__value">Intel "Cascade Lake"</td>
      </tr>
      <tr>
        <th class="c-data-list__key">RAM/Node</th>
        <td class="c-data-list__value">192GB</td>
      </tr>
      <tr>
        <th class="c-data-list__key">Network</th>
        <td class="c-data-list__value">200Gb/s Mellanox Infiniband</td>
      </tr>
      <tr>
        <th class="c-data-list__key">Peak Performance</th>
        <td class="c-data-list__value">38.8 PetaFLOPS</td>
      </tr>
      <tr>
        <th class="c-data-list__key">System Memory</th>
        <td class="c-data-list__value">1.54PB</td>
      </tr>
    </tbody>
</table>
```

[Source.](https://frontera-portal.tacc.utexas.edu/system/) And, I apologize I do not have this in the pattern library yet. [It is coming.](https://github.com/TACC/Core-Styles/commits/main)﹡

<sup>﹡ Commits from Nov 9 to Nov 4 are all pattern documentation and support for it.</sup>

</details>

[^1]: E.g. `<label>`.
[^2]: E.g. `field-...`, `select`, `required`.
[^3]: Because content is not a form (user input), it is data display (_static_ server output).

**Comment by wesleyboar** [comment]
Great work on making this functional, @edmondsgarrett.

I forget how difficult it is to develop with data in the limitations of the local env.

When you have time for the UI, feel free to ask any questions.

**Review by wesleyboar — COMMENTED** [review]
✅ UI matches expectation.

Keith is more familiar with functionality.

I defer to his approval for this.

**Comment by wesleyboar** [comment]
Re-reviewed. 👍 My previous comment still holds https://github.com/TACC/Core-CMS-Custom/pull/44#pullrequestreview-1176744385.

**Review by Strmiska — APPROVED** [review]
Tested locally, the updated modal design is appearing in the registrations table. LGTM!

**Review by wesleyboar — APPROVED** [review]

**Pull request merged**
