### PR TITLE
bug/WP-459: Fix dispatch for reaching submitter admin's list registrations page

### PR DESCRIPTION
**Pull request by edmondsgarrett**
## Overview
Adjust dispatch() used in SubmittersTable that is currently preventing APCD Submitter admins from reaching their registrations listing page + change user group checks in renewal listing + form
…

## Related

- [WP-459](https://jira.tacc.utexas.edu/browse/WP-459)
…

## Changes
- Now using the base `dispatch()` method from `TemplateView` class (what RegistrationsTable is built on top of, which SubmittersTable is then built from)
- Instead of using `get_user_role` to check user's permissions for renewal listing + form, instead use CMS groups via `has_groups` util function
…

## Testing

1. Go to https://localhost:8000/admin and set your user's Chosen Groups to just `SUBMITTER_ADMIN`
2. Now go to https://localhost:8000/register/list-registration-requests and confirm listing comes up
3. In one of the entries on this listing, click through the 'Actions' dropdown to get to 'Renew Registration' and confirm you are directed to the registration form with the data populated from that record
4. Repeat steps 2 & 3 with the following roles and confirm the following:
    - `APCD_ADMIN`: the same results as `SUBMITTER_ADMIN`
    - `SUBMITTER_USER`: the listing does not show and instead you are redirected to https://localhost:8000/

## UI

…

### CODE REVIEW

**Comment by sophia-massie** [comment]
I'm no longer being redirected to the homepage, but the register/list-registration-requests/ page is empty. Trying to debug to find out what's going on. Where you seeing the registration list as only a submitter_admin? Trying to figure out what I could be doing differently.

**Comment by edmondsgarrett** [comment]
> I'm no longer being redirected to the homepage, but the register/list-registration-requests/ page is empty. Trying to debug to find out what's going on. Where you seeing the registration list as only a submitter_admin? Trying to figure out what I could be doing differently.

Yeah, `SUBMITTER_ADMIN` has been working for me on this branch.

**Review by sophia-massie — APPROVED** [review]
LGTM - tested as an apcd_admin, submitter_admin, both submitter_admin and apcd_admin, as well as a submitter_user. The table appeared or didn't appear as expected for each combination of roles.

**Comment by sophia-massie** [comment]
> I'm no longer being redirected to the homepage, but the register/list-registration-requests/ page is empty. Trying to debug to find out what's going on. Where you seeing the registration list as only a submitter_admin? Trying to figure out what I could be doing differently.

This resolved itself - seemed to be a cache issue

**Pull request merged**
