### PR TITLE
task/WP-383: Allow user input of registration year

### PR DESCRIPTION
**Pull request by edmondsgarrett**
## Overview
Per UTH, now allow user to write in registration year on registration form
…

## Related

- [WP-383](https://jira.tacc.utexas.edu/browse/WP-383)
…

## Changes
- Added `input type=number` field for Registration Year on registration form, with min value of `2023`
- On create and update registration db functions, changed value written to database for `registration_year` to value from form
- Added 'Registration Year' field to view registration modal + corresponding Django context object
…

## Testing

1. Go to https://localhost:8000/register/request-to-submit
2. Check for new field "Registration Year" on top of form, and ensure it accepts no values other than int values starting at 2023
3. On successful submit of form, go to https://localhost:8000/administration/list-registration-requests and confirm your record is on the table and the registration year you entered shows up in the corresponding 'Registration Year' column
4. On that record, go to 'View Record' action in the 'Actions' drop down and confirm the registration year shows up there
5. Now, on the 'Edit Record' action, write a different value in the 'Registration Year' and submit that change
6. On reload, confirm the changed year is in those same places
7. Go to https://localhost:8000/register/list-registration-requests and initiate a registration renewal
8. On the renewal form, confirm the value for 'Registration Year' is pre-populated with the registration year of the record you are renewing + 1 (i.e. for a record w/ registration year `2023`, this field should show `2024`)
9. Submit registration renewal and, on https://localhost:8000/administration/list-registration-requests, confirm the correct year is shown on the record

## UI
Registration Form
image

View Registration modal
image

…

### CODE REVIEW

**Comment by sophia-massie** [comment]
Thanks Garrett! Just a couple of bugs I'm seeing:

- I put in year 11111 and it didn't stop me from inserting that. Is that ok?

- I'm getting a bug where if I select a type of file, it's not letting me submit. 

Screenshot 2023-11-10 at 2 38 14 PM

**Review by sophia-massie — CHANGES_REQUESTED** [review]
Looking good. A few bugs that need addressing but should be good to go after that.

**Comment by sophia-massie** [comment]
> Thanks Garrett! Just a couple of bugs I'm seeing:
> 
> * I put in year 11111 and it didn't stop me from inserting that. Is that ok?
> * I'm getting a bug where if I select a type of file, it's not letting me submit.
> 
> Screenshot 2023-11-10 at 2 38 14 PM

Actually, is this because I selected a provider file? Does that not count as a required selection?

**Comment by edmondsgarrett** [comment]
> > Thanks Garrett! Just a couple of bugs I'm seeing:
> > 
> > * I put in year 11111 and it didn't stop me from inserting that. Is that ok?
> > * I'm getting a bug where if I select a type of file, it's not letting me submit.
> > 
> > Screenshot 2023-11-10 at 2 38 14 PM
> 
> Actually, is this because I selected a provider file? Does that not count as a required selection?

Hey Sophia, correct, Blayton from UTH specified that only Medical, Pharmacy, and/or Dental must be chosen; Provider is still optional.

**Comment by edmondsgarrett** [comment]
> Thanks Garrett! Just a couple of bugs I'm seeing:
> 
> * I put in year 11111 and it didn't stop me from inserting that. Is that ok?
> * I'm getting a bug where if I select a type of file, it's not letting me submit.
> 
> Screenshot 2023-11-10 at 2 38 14 PM

Good point, I meant to put a realistic bound on that field, I'll add that now

**Comment by happycodemonkey** [comment]
Did we want to disable the text box scroll thing here? Should be fine for now if that's a lot of extra effort

**Comment by happycodemonkey** [comment]
> Did we want to disable the text box scroll thing here? Should be fine for now if that's a lot of extra effort

It doesn't seem to be scrolling with the mouse so safe to ignore i'd say

**Review by happycodemonkey — APPROVED** [review]
Looks good

**Review by sophia-massie — APPROVED** [review]

**Pull request merged**
