### PR TITLE
task/FP-1816-Extension-Request

### PR DESCRIPTION
**Pull request by sophia-massie**
## Overview

- Created form to submit extension request

## Related

- [FP-1816](https://jira.tacc.utexas.edu/browse/FP-1816)
- requires https://github.com/TACC/Core-CMS-Custom/pull/75

## Changes

- Modified APCD_Database utils to create a extension entry and a get gubmitter for extension and exception since they require the same information to be submitted to the DB with the form submission
- Created add/remove button to add extension time frame information for up to 5 extension requests
- Created path to be submissions/exception-request

## Testing

1. Go to http://localhost:8000/submissions/extension-request/
2. Use snippet on line 20 of extension/views.py making sure to put in your CMS username in the placeholder text
    <details><summary>Snippet</summary>

         [(1, "TESTGOLD", 10000000, "yourusernamehere")]

     </details>
3.  Make sure you have to abide by helper text directions for input on fields
4. Dates can be in past - no limit here since there's no specification from UT Health at this point
5. Should get Credentials Required error that creates a ticket.

## UI
Screen Shot 2023-01-27 at 10 51 59 AM

Screen Shot 2023-01-27 at 10 52 26 AM

Screen Shot 2023-01-27 at 10 52 48 AM
Screen Shot 2023-01-27 at 10 53 16 AM

## Notes
Need this on staging to test if, once it's past the credentials check, that it adds input from the add extension button fields

### CODE REVIEW

**Review by fnets — COMMENTED** [review]
Code looks good so far, trying to get back into the portal to test it.

**Review by fnets — COMMENTED** [review]
Looks like I spoke too soon, there's some conflicts that should be resolved:

`apcd-cms/src/taccsite_cms/custom_app_settings.py
apcd-cms/src/taccsite_cms/urls_custom.py`

**Review by shayanaijaz — APPROVED** [review]
LGTM! Page loads correctly in the portal and error handling working as expected

**Review by fnets — CHANGES_REQUESTED** [review]
Everything LGTM, just need those conflicts resolved.

**Comment by sophia-massie** [comment]
> Everything LGTM, just need those conflicts resolved.

Conflicts are now resolved and ready to merge.

**Review by sophia-massie — COMMENTED** [review]
Resolved conflicts

**Review by fnets — APPROVED** [review]
Great! Thanks for the changes. Super readable

**Pull request merged**
