### PR TITLE
modified to allow filter with ampersand and parens

### PR DESCRIPTION
**Pull request by davidmtacc**
## Overview

…Modified filter javascript to be able to work with ampersands and parens

## Related

…

## Changes
changed ampersand in filter to html entitiy and parens into spaces
…

## Testing

Tested using fake data
  
            user_content = [
            (
                6,
                4,
                'aw@heck.org',
                'Jon Heck',
                'UHC & Nop',
                'no create',
                'none update',
                'no notes',
                't',
                'submitter'

            ),
            (
                5,
                4,
                'aw@heck.org',
                'Jon Heck',
                't and (t)',
                'no create',
                'none update',
                'no notes',
                't',
                'submitter'

            ),
             (
                 5,
                 4,
                'aw@heck.org',
                'Jon Heck',
                'UHC',
                'no create',
                'none update',
                'no notes',
                't',
                'submitter'
            ),           
            
        ]

## UI

…

### CODE REVIEW

**Review by edmondsgarrett — APPROVED** [review]
LGTM!

**Review by sophia-massie — CHANGES_REQUESTED** [review]
Same issue here as in PR #125.

Look like some things Frank requested be removed from view_users/views.py snuck back into the code as per PR #90 :
Merging in main to this branch may solve this issue. Try that first and then if that doesn't work, here are the things that need to be removed @davidmtacc :

On view_users/views.py remove:

_set_modal_content on line 40
actions = "View" on line 22
remove entire line 51 user_view = [usr for usr in user_content if usr[1] == user[0]]

**Comment by davidmtacc** [comment]
Lines removed as suggested

**Review by sophia-massie — APPROVED** [review]
LGTM! Just need to get the latest main into this branch and should be good to go

**Comment by davidmtacc** [comment]
The latest commit confirm views.py as prescribed. Also the script shows as allowing the filter to work with ampersands and parens.
Screenshot 2023-03-15 at 8 45 27 AM
Screenshot 2023-03-15 at 8 45 47 AM

**Comment by davidmtacc** [comment]
Please review. I deleted spaces in views.py which caused conflicts.

**Review by edmondsgarrett — APPROVED** [review]
LGTM

**Review by sophia-massie — APPROVED** [review]
LGTM!

**Pull request merged**
