### PR TITLE
task/WP-391: Entities feedback UTH

### PR DESCRIPTION
**Pull request by edmondsgarrett**
## Overview
Addresses a bug + improvement to the entities on the registration form
…

## Related

- [WP-391](https://jira.tacc.utexas.edu/browse/WP-391)
…

## Changes
- Made all `input` fields for NAIC and License codes type `text`, and simplified field audits to check for up-to 10 digits (addresses both UTH request and bug for values that are too large being written to db and failing, killing the entire entity)
- Added `small` element to the Medicaid choice for plan type w/ helper text per UTH
…

## Testing

1. Go to https://localhost:8000/register/request-to-submit
2. Fill out the form as normal up to the entities, then confirm:
     - For the license and NAIC code fields, only values between 0 (as well 0000000000) and 9999999999 are accepted
     - Some small text saying "(for state use only)" appears next to the "Medicaid" option under "Type of Plan" checklist (see image below in UI section for reference)
     - Repeat for any # of additional entity entries
3. Repeat step 2 and all sub-steps for the following:
     - https://localhost:8000/administration/list-registration-requests > any record > Actions column > Edit Record
     - https://localhost:8000/register/list-registration-requests > any record > Actions column > Renew Registration
     

## UI
image

…

### CODE REVIEW

**Review by mjames-uth — APPROVED** [review]
Looks good

**Review by sophia-massie — CHANGES_REQUESTED** [review]
I submitted a new registration form with the following values. When I looked in the admin table, the NAIC or License number was listed as None for all 5 entities.  Is this expected if I used values like 0000000000, 0, 9999999999? I also tried editing this record with these values, and the view record modal on the admin table is still showing them as None. Each submission is successful however it's just not storing these values for license and NAIC.

on-behalf-of: true
reg_year: 2023
type: tpa_aso
business-name: Sophia Test Nov 16
mailing-address: 111 Test Ave
city: Austin
state: TX - Texas
zip_code: 78745
entity_name_1: Sophia Entity 1
fein_1: 
license_number_1: 0000000000
naic_company_code_1: 
types_of_plans_medicare_1: on
types_of_files_provider_1: on
types_of_files_medical_1: on
total_covered_lives_1: 100
claims_encounters_volume_1: 100
total_claims_value_1: 100
entity_name_2: Sophia Entity 2
fein_2: 
license_number_2: 0
naic_company_code_2: 
types_of_plans_medicare_2: on
types_of_files_provider_2: on
types_of_files_pharmacy_2: on
total_covered_lives_2: 200
claims_encounters_volume_2: 200
total_claims_value_2: 200
entity_name_3: Sophia Entity 3
fein_3: 
license_number_3: 
naic_company_code_3: 0
types_of_plans_medicaid_3: on
types_of_files_medical_3: on
total_covered_lives_3: 300
claims_encounters_volume_3: 300
total_claims_value_3: 300
entity_name_4: Sophia Entity 4
fein_4: 
license_number_4: 
naic_company_code_4: 9999999999
types_of_plans_medicaid_4: on
types_of_files_medical_4: on
total_covered_lives_4: 400
claims_encounters_volume_4: 400
total_claims_value_4: 400
entity_name_5: Sophia Entity 5
fein_5: 
license_number_5: 
naic_company_code_5: 0
types_of_plans_medicare_5: on
types_of_files_medical_5: on
total_covered_lives_5: 500
claims_encounters_volume_5: 500
total_claims_value_5: 500
contact_type: Admin
contact_name: Sophia Massie-Perez
contact_phone: 888 999-2222
contact_email: test@test.com

**Review by sophia-massie — CHANGES_REQUESTED** [review]
I think the style sheet that named the rows for the register/list-registration-requests may have been removed so now the rows don't have the corresponding names. See screen shot below. Either it was unlinked or removed. I don't see that change in this PR but that style sheet should be added back so the rows have the correct names.

Screenshot 2023-11-17 at 12 45 58 PM

**Review by sophia-massie — APPROVED** [review]
LGTM thanks for the changes!

**Pull request merged**
